# Configuration for the local costmap - RUN FROM DOCKER

local_costmap:
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 5.0
  publish_frequency: 5.0
  transform_tolerance: 2.0
  static_map: false
  rolling_window: true
  width: 6.0
  height: 6.0
  resolution: 0.05
  obstacle_range: 6.0
  raytrace_range: 6.0
  footprint: [
      [-0.325, -0.325],
      [-0.325, 0.325],
      [0.325, 0.325],
      [0.46, 0.0],
      [0.325, -0.325]
    ]
  plugins:
    - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
  obstacle_layer:
    observation_sources: base_scan
    base_scan:
      data_type: LaserScan
      topic: /scan
      sensor_frame: rslidar
      marking: true
      clearing: true
    track_unknown_space: false
  inflation_layer:
    #inflation_radius: 0.9
    inflation_radius: 0.9
    cost_scaling_factor: 5.0

