# Common costmap parameters - RUN FROM DOCKER
# Shared settings for global and local costmaps

# Maximum range at which obstacles are considered
obstacle_range: 6.0
# Maximum range at which to perform ray tracing

raytrace_range: 6.0
# Inflation radius for obstacles in the costmap
inflation_radius: 0.9

footprint: [
    [-0.325, -0.325],
    [-0.325, 0.325],
    [0.325, 0.325],
    [0.46, 0.0],
    [0.325, -0.325]
  ]
  
# List of observation sources used for updating the costmap
observation_sources: base_scan
# Configuration for the base_scan observation source
base_scan: {
    sensor_frame: rslidar,
    data_type: LaserScan,
    topic: /scan,
    marking: true,
    clearing: true,
  }
